name: fl_anchor_scroll
description: "ScrollView anchor scrolling supports tab switching linkage"
version: 0.0.1
repository: https://github.com/Wayaer/fl_anchor_scroll.git

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_lints: ^3.0.1

flutter:
